#!/usr/bin/env bash
# Clone (or refresh) the external skill libraries Claude must consult on every task,
# then rebuild .claude/external-skills/INDEX.md. Safe to re-run; never fails the session.
set -u

ROOT="${CLAUDE_PROJECT_DIR:-$(git -C "$(dirname "$0")" rev-parse --show-toplevel)}"
DEST="$ROOT/.claude/external-skills"
REPOS=(
  anthropics/skills
  vercel-labs/agent-skills
  nextlevelbuilder/ui-ux-pro-max-skill
  bencium/bencium-marketplace
  AccessLint/skills
)

mkdir -p "$DEST"
for repo in "${REPOS[@]}"; do
  dir="$DEST/${repo%%/*}__${repo##*/}"
  if [ -d "$dir/.git" ]; then
    git -C "$dir" fetch -q --depth 1 origin HEAD && git -C "$dir" reset -q --hard FETCH_HEAD \
      || echo "warn: could not refresh $repo (using existing copy)" >&2
  else
    git clone -q --depth 1 "https://github.com/$repo.git" "$dir" \
      || echo "warn: could not clone $repo" >&2
  fi
done

# Build an index of every skill: name, description, path.
INDEX="$DEST/INDEX.md"
python3 - "$ROOT" "$DEST" "${REPOS[@]}" > "$INDEX" <<'PY_INDEX'
import pathlib, re, sys
root, dest, repos = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3:]
skip = ("node_modules", "cli/assets", "/template/")

def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---", text, re.S)
    fields, key = {}, None
    for line in (m.group(1).splitlines() if m else []):
        kv = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if kv:
            key, val = kv.group(1), kv.group(2).strip()
            fields[key] = "" if val in (">", "|", ">-", "|-") else val.strip("'\"")
        elif key and line.startswith((" ", "\t")):
            fields[key] = (fields[key] + " " + line.strip()).strip()
    return fields

print("# External skills index\n")
print("Generated by scripts/sync-external-skills.sh. Read the SKILL.md at the listed path before using a skill.")
for repo in repos:
    d = dest / repo.replace("/", "__")
    if not d.is_dir():
        continue
    print(f"\n## {repo}\n")
    for f in sorted(d.rglob("SKILL.md")):
        if any(s in str(f) for s in skip):
            continue
        fm = frontmatter(f.read_text(errors="ignore"))
        desc = fm.get("description") or "(no description)"
        desc = desc if len(desc) <= 240 else desc[:237] + "..."
        print(f"- **{fm.get('name') or f.parent.name}** — {desc} — `{f.relative_to(root)}`")
PY_INDEX

echo "External skills ready: $DEST (index: $INDEX)"
exit 0
